COUNTRIES_DESIRED = [
    'Albania',
    'Germany',
    'Andorra',
    'Austria',
    'Belarus',
    'Belgium',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Denmark',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Estonia',
    'Finland',
    'France',
    'Greece',
    'Hungary',
    'Ireland',
    'Iceland',
    'Italy',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Kosovo',
    'North Macedonia',
    'Malta',
    'Moldavia',
    'Monaco',
    'Montenegro',
    'Norway',
    'Netherlands',
    'Poland',
    'Portugal',
    'UK',
    'Czech Republic',
    'Romania',
    'Russia',
    'San Marino',
    'Serbia',
    'Sweden',
    'Switzerland',
    'Ukraine',
    'Vatican',
    'Antigua and Barbuda',
    'Bahamas',
    'Barbados',
    'Belize',
    'Canada',
    'Costa Rica',
    'Cuba',
    'Dominica',
    'El Salvador',
    'United States of America',
    'Grenada',
    'Guatemala',
    'Haiti',
    'Honduras',
    'Jamaica',
    'Mexico',
    'Nicaragua',
    'Panama',
    'Dominican Republic',
    'Saint Lucia',
    'Saint Kitts and Nevis',
    'Saint Vincent and the Grenadines',
    'Trinidad and Tobago',
    'Afghanistan',
    'Saudi Arabia',
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Burma',
    'Brunei',
    'Bhutan',
    'Cambodia',
    'Qatar',
    'Kazakhstan',
    'China',
    'Cyprus',
    'South Korea',
    'North Korea',
    'United Arab Emirates'
    'Philippines',
    'Georgia',
    'Yemen',
    'India',
    'Indonesia',
    'Will',
    'Iraq',
    'Israel',
    'Kuwait',
    'Japan',
    'Jordan',
    'Malaysia',
    'Maldives',
    'Mongolia',
    'Laos',
    'Lebanon',
    'Nepal',
    'Oman',
    'Pakistan',
    'Kyrgyzstan',
    'Singapore',
    'Syria',
    'Sri Lanka',
    'Thailand',
    'Taiwan',
    'Tajikistan',
    'East Timor',
    'Turkey',
    'Turkmenistan',
    'Uzbekistan',
    'Vietnam',
    'Australia',
    'Federated States of Micronesia',
    'Fiji',
    'Marshall Islands',
    'Solomon Islands',
    'Kiribati',
    'Nauru',
    'New Zealand',
    'Palau',
    'Papua New Guinea',
    'Samoa',
    'Tonga',
    'Tuvalu',
    'Vanuatu',
    'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela',
    'South Africa',
    'Angola',
    'Algeria',
    'Benin',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Cape Green',
    'Cameroon',
    'Chad',
    'Comoros',
    'Costa do Marfim',
    'Djibouti',
    'Egypt',
    'Eritrea',
    'Ethiopia',
    'Gabon',
    'Gambia',
    'Ghana',
    'Guinea',
    'Guinea Bissau',
    'Equatorial Guinea',
    'Lesotho',
    'Liberia',
    'Libya',
    'Madagascar',
    'Malawi',
    'Mali',
    'Morocco',
    'Mauritius',
    'Mauritania',
    'Mozambique',
    'Namibia',
    'Niger',
    'Nigeria',
    'Kenya',
    'Central African Republic',
    'Democratic Republic of the Congo',
    'Republic of Congo',
    'Rwanda',
    'Sao Tome and Principe',
    'Senegal',
    'Sierra Leone',
    'Seychelles',
    'Somalia',
    'Swaziland',
    'Sudan',
    'Southern Sudan',
    'Tanzania',
    'Togo',
    'Tunisia',
    'Uganda',
    'Zambia',
    'Zimbabwe',
    ]